<select>:
	
	orientation: "vertical"
			
		
	size_hint: 0.2,1
			
	Button:
		text: "Kare"
		on_press: root.sekil_core()
	Button:
		text: "Elips"
		on_press: root.sekil_elips()
	Button:
		text: "cizgi"
		on_press: root.sekil_line()
	Button:
		text: "kırmızı"
		on_press: root.renk_red()
	Button:
		text: "Mavi"
		on_press: root.renk_blue()
	Button:
		text: "yesil"
		on_press: root.renk_green()
				
		